### ISSUE TITLE
Patches for 4.38.23038

### ISSUE THREAD

**Issue by anrxc** [geek1011/kobopatch-patches#133]
After a year of no development they released **4.38.23038** for most devices. 

Changelog: 

   • Fixed: The eReader may crash while scrolling or swiping in the 'Discover' tab

   • Fixed: The eReader database may be left in an incorrect state after connecting and disconnecting the eReader from a computer

**Comment by anrxc** [comment]
Duplicate of #135

**Comment by anrxc** [comment]
Duplicate of #135

**Comment by X4LD1M0** [comment]
@anrxc can I ask what the reason if for not creating a patch for release 4.38.23038?
