### ISSUE TITLE
Add release notes and latest version to webpage

### ISSUE THREAD

**Issue by geek1011** [geek1011/kobopatch-patches#29]

**Comment by geek1011** [comment]
@NiLuJe, Can you take a quick look at it: https://pgaskin.net/kobopatch-patches?

**Comment by NiLuJe** [comment]
I'd make the headline a link to the landing page (to complement the "Back" link), but besides this small nit, LGTM ;).

**Comment by geek1011** [comment]
@NiLuJe, it [seems](https://github.com/just-install/registry/pull/168) that GitHub now supports linking to a file in the latest release, like github.com/geek1011/kobopatch-patches/releases/latest/download/kobopatch_4.18.13737.zip .
