### ISSUE TITLE
Mention the string-mangling potential of some patches in their comment

### ISSUE THREAD

**Issue by NiLuJe** [geek1011/kobopatch-patches#34]
In particular, that [bit of the FAQ](https://www.mobileread.com/forums/showthread.php?p=3697840#post3697840) in the relevant patch (libnickel's Rename new home screen footer).

(Brought on by trekk's report over [here](https://www.mobileread.com/forums/showthread.php?t=314220&page=12) of it eating the "o" in the German keyboard layout).

I didn't even remember that this could happen, tshering remembered something about it, and Semwize pointed out to us that it was in fact mentioned in the FAQ ;p.

**Comment by geek1011** [comment]
Yes, this is an issue with many of the patches due to optimization. The biggest barrier to pointing it out is that it changes every version or so (a few versions ago, the home screen ones messed up the account settings, but not as of the last one IIRC).
