### ISSUE TITLE
'Increase headlines font' nickel patch not working for LibraH2O

### ISSUE THREAD

**Issue by jackiew1** [geek1011/kobopatch-patches#45]
oren64's nickel patch **'Increase headlines font'** not working for LibraH2O. See https://www.mobileread.com/forums/showpost.php?p=3931895&postcount=177

Semwize has provided the necessary Find/Replaces so I'm going to commit an update and change the Description to be a bit more helpful about what it actually does.

**Comment by geek1011** [comment]
A hint: you can put "closes #45" instead of just "#45" in the commit title to automatically close this issue when you commit it.
