### ISSUE TITLE
"Fix three KePub fullScreenReading bugs" Better Patch

### ISSUE THREAD

**Issue by sekkit** [geek1011/kobopatch-patches#5]
the 3 patches still not working for Japanese(Vertical) and English.

**Comment by sekkit** [comment]
I think change 0.Xem to XXpx could be better in compatibility.
Because fonts differs in weight & sizes, I tested many works, few(very few) like MI LANTING still cut off Japanese with this patch. BUT default fonts all works fine.

**Comment by geek1011** [comment]
This patch should not be necessary since 4.11.11911, as Kobo now officially supports disabling headers and footers.
