### ISSUE TITLE
"Change dicthtml strings to micthtml" doesn't work completely on 4.20

### ISSUE THREAD

**Issue by rtiangha** [geek1011/kobopatch-patches#53]
I posted about my experience [here](https://www.mobileread.com/forums/showpost.php?p=3960208&postcount=14), but basically, the patch applies without errors, but the full list of dictionaries doesn't appear in the drop down box; just a small subset. And the Settings menu thinks there are no dictionaries installed, despite the Installed and IsSynced columns in the database all being set to true and the micthtml files all being there. And you can still do searches on the dictionaries that are selectable, meaning that changing the file name does work since the Kobo can still access them.

Remove the patch and rename everything to dicthtml format, and everything works as expected again. Patch worked fine in 4.19 and earlier.

**Comment by geek1011** [comment]
I'm most likely going to remove the patch, as it's quite old, and it's not necessary (I think).

Can someone else confirm that setting IsSynced to false on an overwritten installed built-in dictionary prevents it being overwritten during a sync?

**Comment by geek1011** [comment]
This patch isn't necessary anymore: https://github.com/geek1011/kobopatch-patches/issues/49#issuecomment-596228361.
