### ISSUE TITLE
Re-jig patch 'Dictionary pop-up - increase available text area'

### ISSUE THREAD

**Issue by jackiew1** [geek1011/kobopatch-patches#58]
Kobo added a new CSS stream (nickel nozlib `DictionaryViewFooter`) to control footer height of dictionary pop-up. I'm going to roll this into existing nickel patch `Dictionary pop-up - increase available text area` rather than add an extra one.

@geek1011 @NiLuJe 
Some of the dictionary pop-up variables in nickel don't have specific `qApp_deviceIsStorm` values. In this situation does the LibraH2O use Dragon or Daylight values?

**Comment by geek1011** [comment]
See here: MR:thread-325471

![](https://www.mobileread.com/forums/attachment.php?attachmentid=175475&d=1575854799)

Kobo uses a three-layered approach for device codenames.

**Comment by jackiew1** [comment]
Thanks, so it's Dragon.

**Comment by jackiew1** [comment]
@geek1011 Update commited, but I'll leave you to decide when to close it. It's been tested with Glo, Aura6", AuraHD, H2O, ClaraHD, KA1, Forma.

If you want to test with your Mini Trilogy device then all you need to do is enable as-is and check that the dictionary pop-up with the built-in English dictionary doesn't look terrible.

**Comment by geek1011** [comment]
Looks good!
