### ISSUE TITLE
add missing letter replacement for Hebrew keyboard (GloHD/ClaraHD/AuraOne/H2O2):

### ISSUE THREAD

**Issue by lilymike** [geek1011/kobopatch-patches#8]
based on latest Cyrillic keyboard update to "libnickel.so.1.0.0.yaml" there is also a need to update the missing line for the Hebrew keyboard (GloHD/ClaraHD/AuraOne/H2O2):
- ReplaceString: {Offset: -56, Find: "ß\0", Replace: "ן"}

here it is in the context of the file:
Hebrew keyboard (GloHD/ClaraHD/AuraOne/H2O2):
  - Enabled: no
  - PatchGroup: Keyboard alternatives
    ## Replaces keys on the Extended Latin keypad with Hebrew alternatives.
    ##
    ## Note that after the device boots, the keypad might just show blank squares
    ## until after the first book has been opened.
    ## Also note that long-pressing keys on the base keypad will no longer show
    ## the appropriate list of Extended Latin keys.
    #
    # Replace layout sign
  - FindBaseAddressString: "ÉÀÇ"
  - ReplaceString: {Offset: 0, Find: "ÉÀÇ", Replace: "אב"}
    # Change keyboard layout
  - FindBaseAddressString: "ý\0\0ÿ\0\0š\0\0ž\0\0"
    # Top row, left to right (10 keys):
  - ReplaceString: {Offset: 0x00, Find: "ý\0", Replace: "/"}
  - ReplaceString: {Offset: 0x04, Find: "ÿ\0", Replace: "'"}
  - ReplaceString: {Offset: 0x08, Find: "š\0", Replace: "ק"}
  - ReplaceString: {Offset: 0x0C, Find: "ž\0", Replace: "ר"}
  - ReplaceString: {Offset: 0x10, Find: "æ\0", Replace: "א"}
  - ReplaceString: {Offset: 0x14, Find: "œ\0", Replace: "ט"}
  - ReplaceString: {Offset: 0x18, Find: "þ\0", Replace: "ו"}
  **- ReplaceString: {Offset: -56, Find: "ß\0", Replace: "ן"}**
  - ReplaceString: {Offset: 0x1C, Find: "ĳ\0", Replace: "ם"}
  - ReplaceString: {Offset: 0x20, Find: "ŀ\0", Replace: "פ"}

**Comment by geek1011** [comment]
Done. Will be released in v39 for firmwares `4.11.11980` `4.11.11982` `4.11.12019` `4.12.12111` along with the next update to the rest of the patches.

**Comment by lilymike** [comment]
thank you

**Comment by lilymike** [comment]
the issue is not resolved yet

**Comment by geek1011** [comment]
Sorry, I forgot all about it. I'll do it later today.
